controller_list:
  - name: fake_hcr_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
initial:  # Define initial robot poses per group
  - group: hcr_arm
    pose: hcr_home